baseURL = "https://pro-mrurenko.netlify.app/"
languageCode = "ru-Ru"
title = "Maxim Rurenko"
theme = "hugo-mr-pro"
defaultContentLanguage='ru'
defaultContentLanguageInSubdir = false

[params]
    author = "Максим Руренко"
    info = "Software Developer"
    description = "Maxim Rurenko's personal website"
    keywords = "blog,developer"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    customCSS = ["css/custom.css"]
    customPrintCSS = ["css/print.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/renkoru/"

# Menu links
# [[menu.main]]
#     name = "About"
#     weight = 3
#     url = "/about/"
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "Articles"
#     weight = 2
#     url  = "/articles/"

[languages]
  [languages.ru]
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-Ru'
    languageDirection = 'ltr'
    languageName = 'Russian'
    title = 'Максим Руренко'
    weight = 1
    [languages.ru.params]
      subtitle = 'subtitle placeholder'
    [languages.ru.menus]
      [[languages.ru.menus.main]]
        name = 'Публикации'
        pageRef = '/articles'
        weight = 1
      [[languages.ru.menus.main]]
        name = 'Обо мне'
        pageRef = '/about'
        weight = 2
  [languages.en]
    contentDir = 'content/en'
    disabled = true
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

# (not working) Module way to use theme
# [module]
# [[module.imports]]
#   path = 'github.com/renkoru/hugo-mr-pro'
